apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: lesson15
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: localhost2030/lesson1:v0.2
        ports:
        - containerPort: 8080

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: declarative-deployment
#   labels:
#     app: go-web
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: goapp
#   template:
#     metadata:
#       labels:
#         app: goapp
#     spec:
#       containers:
#       - name: goapp
#         image: localhost2030/lesson1:v0.2
#         ports:
#         - containerPort: 8080